flat_dev_1_data.Rmd:
  path: dev/flat_dev_1_data.Rmd
  state: active
  R:
  - R/fetch_fts_data.R
  - R/filter_flows_for_indicators.R
  - R/slugify.R
  tests:
  - tests/testthat/test-fetch_fts_data.R
  - tests/testthat/test-filter_flows_for_indicators.R
  - tests/testthat/test-slugify.R
  vignettes: vignettes/1-data-tidying.Rmd
  inflate:
    flat_file: dev/flat_dev_1_data.Rmd
    vignette_name: 1-Data Tidying
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_dev_2_indicator.Rmd:
  path: dev/flat_dev_2_indicator.Rmd
  state: active
  R:
  - R/indicator_cross_donor_systemic_destination_alignment.R
  - R/indicator_destination_dependency.R
  - R/indicator_destination_donor_diversity.R
  - R/indicator_destination_donor_retention.R
  - R/indicator_destination_earmarking_flexibility.R
  - R/indicator_destination_funding_diversity.R
  - R/indicator_destination_funding_stability.R
  - R/indicator_destination_funding_trend.R
  - R/indicator_destination_funding_volatility.R
  - R/indicator_destination_modality_balance.R
  - R/indicator_destination_modality_innovation.R
  - R/indicator_destination_pipeline_visibility.R
  - R/indicator_donor_destination_concentration.R
  - R/indicator_donor_destination_coverage.R
  - R/indicator_donor_destination_earmarking_flexibility.R
  - R/indicator_donor_destination_risk_tolerance.R
  - R/indicator_donor_destination_stability.R
  - R/indicator_donor_destination_trend.R
  - R/indicator_donor_funding_consistency.R
  - R/indicator_donor_funding_growth.R
  - R/indicator_donor_geographic_alignment.R
  - R/indicator_donor_knowledge_sharing_intensity.R
  - R/indicator_donor_recipient_concentration.R
  - R/indicator_donor_recipient_funding_growth.R
  - R/indicator_donor_recipient_reciprocity.R
  - R/indicator_donor_recipient_relationship_duration.R
  - R/indicator_donor_recipient_stability.R
  - R/indicator_donor_recipient_trend.R
  - R/indicator_donor_relationship_duration.R
  - R/indicator_donor_sector_alignment.R
  - R/indicator_donor_systemic_concentration.R
  - R/indicator_donor_timing_consistency.R
  - R/indicator_recipient_amount_stability.R
  - R/indicator_recipient_cofunding_rate.R
  - R/indicator_recipient_funding_share.R
  - R/indicator_recipient_systemic_diversification.R
  tests:
  - tests/testthat/test-indicator_donor_funding_consistency.R
  - tests/testthat/test-indicator_donor_relationship_duration.R
  - tests/testthat/test-indicator_donor_funding_growth.R
  - tests/testthat/test-indicator_donor_timing_consistency.R
  - tests/testthat/test-indicator_donor_systemic_concentration.R
  - tests/testthat/test-indicator_donor_knowledge_sharing_intensity.R
  - tests/testthat/test-indicator_donor_sector_alignment.R
  - tests/testthat/test-indicator_donor_geographic_alignment.R
  - tests/testthat/test-indicator_cross_donor_systemic_destination_alignment.R
  - tests/testthat/test-indicator_donor_recipient_relationship_duration.R
  - tests/testthat/test-indicator_donor_recipient_funding_growth.R
  - tests/testthat/test-indicator_donor_recipient_stability.R
  - tests/testthat/test-indicator_donor_recipient_concentration.R
  - tests/testthat/test-indicator_donor_recipient_trend.R
  - tests/testthat/test-indicator_donor_recipient_reciprocity.R
  - tests/testthat/test-indicator_donor_destination_coverage.R
  - tests/testthat/test-indicator_donor_destination_trend.R
  - tests/testthat/test-indicator_donor_destination_concentration.R
  - tests/testthat/test-indicator_donor_destination_earmarking_flexibility.R
  - tests/testthat/test-indicator_donor_destination_risk_tolerance.R
  - tests/testthat/test-indicator_donor_destination_stability.R
  - tests/testthat/test-indicator_recipient_funding_share.R
  - tests/testthat/test-indicator_recipient_amount_stability.R
  - tests/testthat/test-indicator_recipient_cofunding_rate.R
  - tests/testthat/test-indicator_recipient_systemic_diversification.R
  - tests/testthat/test-indicator_destination_modality_innovation.R
  - tests/testthat/test-indicator_destination_pipeline_visibility.R
  - tests/testthat/test-indicator_destination_earmarking_flexibility.R
  - tests/testthat/test-indicator_destination_donor_diversity.R
  - tests/testthat/test-indicator_destination_funding_stability.R
  - tests/testthat/test-indicator_destination_funding_trend.R
  - tests/testthat/test-indicator_destination_donor_retention.R
  - tests/testthat/test-indicator_destination_funding_diversity.R
  - tests/testthat/test-indicator_destination_funding_volatility.R
  - tests/testthat/test-indicator_destination_dependency.R
  - tests/testthat/test-indicator_destination_modality_balance.R
  vignettes: vignettes/2-indicators.Rmd
  inflate:
    flat_file: dev/flat_dev_2_indicator.Rmd
    vignette_name: 2-Indicators
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_dev_4_analysis.Rmd:
  path: dev/flat_dev_4_analysis.Rmd
  state: active
  R:
  - R/analysis_competitive_intel_matrix.R
  - R/analysis_donor_lifecycle_stage.R
  - R/analysis_donor_network_metrics.R
  - R/analysis_donor_segmentation.R
  - R/analysis_fit_opportunity_model.R
  - R/analysis_funding_forecast.R
  - R/analysis_portfolio_scores.R
  - R/analysis_prepare_opportunity_dataset.R
  - R/analysis_systemic_network_insights.R
  - R/analysis_wordcloud_from_flows.R
  tests:
  - tests/testthat/test-analysis_wordcloud_from_flows.R
  - tests/testthat/test-analysis_systemic_network_insights.R
  - tests/testthat/test-analysis_portfolio_scores.R
  - tests/testthat/test-analysis_prepare_opportunity_dataset.R
  - tests/testthat/test-analysis_fit_opportunity_model.R
  - tests/testthat/test-analysis_competitive_intel_matrix.R
  - tests/testthat/test-analysis_donor_lifecycle_stage.R
  - tests/testthat/test-analysis_donor_segmentation.R
  - tests/testthat/test-analysis_funding_forecast.R
  - tests/testthat/test-analysis_donor_network_metrics.R
  vignettes: vignettes/4-analysis.Rmd
  inflate:
    flat_file: dev/flat_dev_4_analysis.Rmd
    vignette_name: 4-Analysis
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_dev_5_visualisation.Rmd:
  path: dev/flat_dev_5_visualisation.Rmd
  state: active
  R:
  - R/clean_llm_response.R
  - R/generate_plot_story.R
  - R/generate_report.R
  - R/plot_destination_funding_destination.R
  - R/plot_destination_funding_donor.R
  - R/plot_destination_heatmap.R
  - R/plot_donor_cluster_coverage.R
  - R/plot_donor_earmarking.R
  - R/plot_donor_flowtype.R
  - R/plot_donor_funding_over_time.R
  - R/plot_funding_status_timeline.R
  - R/plot_recipient_cofunding.R
  - R/plot_recipient_contribution_type.R
  - R/plot_recipient_funding_composition.R
  - R/plot_recipient_grandbargain.R
  tests:
  - tests/testthat/test-clean_llm_response.R
  - tests/testthat/test-generate_plot_story.R
  - tests/testthat/test-plot_donor_funding_over_time.R
  - tests/testthat/test-plot_donor_earmarking.R
  - tests/testthat/test-plot_donor_flowtype.R
  - tests/testthat/test-plot_donor_cluster_coverage.R
  - tests/testthat/test-plot_recipient_funding_composition.R
  - tests/testthat/test-plot_recipient_grandbargain.R
  - tests/testthat/test-plot_recipient_cofunding.R
  - tests/testthat/test-plot_recipient_contribution_type.R
  - tests/testthat/test-plot_destination_funding_destination.R
  - tests/testthat/test-plot_destination_funding_donor.R
  - tests/testthat/test-plot_destination_heatmap.R
  - tests/testthat/test-plot_funding_status_timeline.R
  - tests/testthat/test-generate_report.R
  vignettes: vignettes/5-visualisation.Rmd
  inflate:
    flat_file: dev/flat_dev_5_visualisation.Rmd
    vignette_name: 5-Visualisation
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
